modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="espcraft"
version="1.0.3"
displayName="ESPcraft"
credits="Special thanks to you, the user."
displayURL="https://www.nvias.org"
logoFile="logo.png"
authors="Nvias"
description='''
A tool for connecting worlds.
'''

[[dependencies.espcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




